descheduler:
  schedule: "0 13 * * 2,4"

  podSecurityContext:
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    runAsGroup: 1000

  nodeSelector:
    kubernetes.io/os: linux

  deschedulerPolicy:
    profiles:
      - name: default
        pluginConfig:
          - name: DefaultEvictor
            args:
              ignorePvcPods: true
              evictLocalStoragePods: true
          - name: RemoveDuplicates
            args: {}
          - name: RemovePodsHavingTooManyRestarts
            args:
              podRestartThreshold: 100
              includingInitContainers: true
          - name: RemovePodsViolatingNodeAffinity
            args:
              nodeAffinityType:
                - requiredDuringSchedulingIgnoredDuringExecution
          - name: RemovePodsViolatingNodeTaints
            args: {}
          - name: RemovePodsViolatingInterPodAntiAffinity
            args: {}
          - name: RemovePodsViolatingTopologySpreadConstraint
            args: {}
          - name: LowNodeUtilization
            args:
              thresholds:
                cpu: 20
                memory: 30
                pods: 30
              targetThresholds:
                cpu: 50
                memory: 75
                pods: 50
        plugins:
          balance:
            enabled:
              - LowNodeUtilization
              - RemoveDuplicates
              - RemovePodsViolatingTopologySpreadConstraint
          deschedule:
            enabled:
              - RemovePodsHavingTooManyRestarts
              - RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingNodeTaints
              - RemovePodsViolatingInterPodAntiAffinity